name: CI

on:
  push:
    branches:
      - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           node-version: "20"

#       - name: Install dependencies
#         run: flutter pub get

#       - name: Run tests
#         run: flutter test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
